# Generated by Django 4.2.23 on 2025-07-21 05:31

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Association',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name="Nom de l'Association")),
                ('logo_association', models.ImageField(blank=True, null=True, upload_to='logos/associations/', verbose_name='Logo Association')),
                ('logo_universite', models.ImageField(blank=True, null=True, upload_to='logos/universites/', verbose_name='Logo Université')),
                ('devise', models.CharField(blank=True, max_length=500, null=True, verbose_name='Devise')),
                ('fondateurs', models.TextField(default='', help_text='Séparez les noms par des virgules', verbose_name="Fondateurs de l'association")),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('date_creation', models.DateField(default=django.utils.timezone.now, verbose_name='Date de création')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Association',
                'verbose_name_plural': 'Associations',
            },
        ),
        migrations.CreateModel(
            name='Membre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom du membre')),
                ('prenom', models.CharField(max_length=100, verbose_name='Prénom du membre')),
                ('numero_cin', models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='Format CIN invalide. Exemple: AB123456', regex='^[A-Z]{1,2}\\d{6,8}$')], verbose_name='N° CIN')),
                ('date_debut', models.DateField(verbose_name='Du')),
                ('date_fin', models.DateField(verbose_name='À')),
                ('filiere', models.CharField(max_length=100, verbose_name='Filière')),
                ('parcours', models.CharField(max_length=100, verbose_name='Parcours')),
                ('numero_carte', models.CharField(max_length=20, unique=True, verbose_name='N°C')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/membres/', verbose_name='Photo du membre')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('association', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membres', to='membres.association')),
            ],
            options={
                'verbose_name': 'Membre',
                'verbose_name_plural': 'Membres',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CarteMembre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_unique', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('date_generation', models.DateTimeField(auto_now_add=True)),
                ('est_imprimee', models.BooleanField(default=False, verbose_name='Carte imprimée')),
                ('date_impression', models.DateTimeField(blank=True, null=True, verbose_name="Date d'impression")),
                ('membre', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='carte', to='membres.membre')),
            ],
            options={
                'verbose_name': 'Carte Membre',
                'verbose_name_plural': 'Cartes Membres',
                'ordering': ['-date_generation'],
            },
        ),
    ]
