# Generated by Django 4.2.22 on 2025-07-21 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membres', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='membre',
            name='adresse',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Adresse ou Cité universitaire'),
        ),
        migrations.AddField(
            model_name='membre',
            name='date_naissance',
            field=models.DateField(blank=True, null=True, verbose_name='Date de naissance'),
        ),
        migrations.AddField(
            model_name='membre',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='membre',
            name='etablissement',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Établissement'),
        ),
        migrations.AddField(
            model_name='membre',
            name='telephone',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Téléphone'),
        ),
    ]
