# Generated by Django 4.2.23 on 2025-07-21 11:58

from django.db import migrations
from datetime import date


def fix_null_dates(apps, schema_editor):
    """Corriger les dates NULL pour les membres existants"""
    Membre = apps.get_model('membres', 'Membre')
    current_year = date.today().year
    
    # Corriger les dates de début NULL
    membres_null_debut = Membre.objects.filter(date_debut__isnull=True)
    if membres_null_debut.exists():
        membres_null_debut.update(date_debut=date(current_year, 9, 1))
    
    # Corriger les dates de fin NULL
    membres_null_fin = Membre.objects.filter(date_fin__isnull=True)
    if membres_null_fin.exists():
        membres_null_fin.update(date_fin=date(current_year + 1, 8, 31))


def reverse_fix_null_dates(apps, schema_editor):
    """Fonction de retour - ne fait rien car on ne peut pas revenir à NULL"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('membres', '0002_membre_adresse_membre_date_naissance_membre_email_and_more'),
    ]

    operations = [
        migrations.RunPython(fix_null_dates, reverse_fix_null_dates),
    ]
