# Generated by Django 4.2.22 on 2025-07-21 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membres', '0003_auto_20250721_1258'),
    ]

    operations = [
        migrations.AddField(
            model_name='association',
            name='logo_fizato',
            field=models.ImageField(blank=True, null=True, upload_to='logos/fizato/', verbose_name='Logo FI.ZA.TO'),
        ),
    ]
