# Generated by Django 4.2.22 on 2025-08-04 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membres', '0004_association_logo_fizato'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membre',
            name='date_debut',
        ),
        migrations.RemoveField(
            model_name='membre',
            name='date_fin',
        ),
        migrations.AddField(
            model_name='membre',
            name='nom_facebook',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nom Facebook'),
        ),
        migrations.AlterField(
            model_name='membre',
            name='numero_carte',
            field=models.CharField(blank=True, max_length=20, unique=True, verbose_name='N°C'),
        ),
    ]
