# Generated by Django 4.2.22 on 2025-08-04 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membres', '0005_remove_membre_date_debut_remove_membre_date_fin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membre',
            name='numero_cin',
            field=models.CharField(help_text="Numéro de Carte d'Identité Nationale", max_length=20, unique=True, verbose_name='N° CIN'),
        ),
    ]
