# Generated by Django 4.2.22 on 2025-08-04 05:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('membres', '0006_alter_membre_numero_cin'),
    ]

    operations = [
        migrations.AddField(
            model_name='membre',
            name='user',
            field=models.OneToOneField(blank=True, help_text='Compte utilisateur associé', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
    ]
