# Generated by Django 4.2.22 on 2025-08-05 01:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('membres', '0007_membre_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='FonctionBureau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom de la fonction')),
                ('niveau_hierarchique', models.PositiveIntegerField(default=1, help_text='1 = Président, 2 = Vice-président, etc.', verbose_name='Niveau hiérarchique')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description de la fonction')),
            ],
            options={
                'verbose_name': 'Fonction du Bureau',
                'verbose_name_plural': 'Fonctions du Bureau',
                'ordering': ['niveau_hierarchique', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='InfoFizato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(default='FI.ZA.TO', max_length=200, verbose_name="Nom de l'organisation")),
                ('nom_complet', models.CharField(blank=True, max_length=500, null=True, verbose_name='Nom complet')),
                ('date_creation', models.DateField(verbose_name='Date de création')),
                ('devise', models.TextField(blank=True, null=True, verbose_name='Devise')),
                ('fondateurs', models.TextField(help_text='Séparez les noms par des virgules', verbose_name='Fondateurs')),
                ('description', models.TextField(verbose_name='Description')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/fizato/', verbose_name='Logo FIZATO')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Information FIZATO',
                'verbose_name_plural': 'Informations FIZATO',
            },
        ),
        migrations.CreateModel(
            name='MembreBureau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField(verbose_name='Date de début de mandat')),
                ('date_fin', models.DateField(blank=True, null=True, verbose_name='Date de fin de mandat')),
                ('est_actuel', models.BooleanField(default=True, verbose_name='Mandat actuel')),
                ('fonction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='membres.fonctionbureau', verbose_name='Fonction')),
                ('membre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='membres.membre', verbose_name='Membre')),
            ],
            options={
                'verbose_name': 'Membre du Bureau',
                'verbose_name_plural': 'Membres du Bureau',
                'ordering': ['fonction__niveau_hierarchique', 'membre__nom'],
                'unique_together': {('membre', 'fonction', 'est_actuel')},
            },
        ),
    ]
