# Generated by Django 4.2.22 on 2025-08-05 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membres', '0008_fonctionbureau_infofizato_membrebureau'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='membrebureau',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='membrebureau',
            constraint=models.UniqueConstraint(condition=models.Q(('est_actuel', True)), fields=('membre', 'fonction'), name='unique_membre_fonction_actuel'),
        ),
    ]
