# Generated by Django 4.2.22 on 2025-08-05 02:13

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('membres', '0009_alter_membrebureau_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComiteDoyen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(default='Membre du Comité des Doyens', max_length=100)),
                ('date_nomination', models.DateField(default=django.utils.timezone.now)),
                ('est_actif', models.BooleanField(default=True)),
                ('ordre_affichage', models.IntegerField(default=1)),
            ],
            options={
                'ordering': ['ordre_affichage', 'date_nomination'],
            },
        ),
        migrations.CreateModel(
            name='Mandat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text='Ex: Mandat 2024-2026', max_length=100)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('est_actuel', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date_debut'],
            },
        ),
        migrations.AddConstraint(
            model_name='mandat',
            constraint=models.UniqueConstraint(condition=models.Q(('est_actuel', True)), fields=('est_actuel',), name='unique_mandat_actuel'),
        ),
        migrations.AddField(
            model_name='comitedoyen',
            name='membre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comite_doyen', to='membres.membre'),
        ),
    ]
