# Generated by Django 4.2.22 on 2025-08-05 03:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('membres', '0010_comitedoyen_mandat_mandat_unique_mandat_actuel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comitedoyen',
            name='date_fin',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comitedoyen',
            name='mandat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comite_doyen', to='membres.mandat'),
        ),
    ]
