# Generated by Django 4.2.22 on 2025-08-05 03:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('membres', '0011_comitedoyen_date_fin_comitedoyen_mandat'),
    ]

    operations = [
        migrations.AddField(
            model_name='membrebureau',
            name='mandat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='membres_bureau', to='membres.mandat'),
        ),
    ]
