# Generated by Django 4.2.22 on 2025-08-05 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membres', '0012_membrebureau_mandat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mandat',
            name='date_fin',
            field=models.DateField(blank=True, null=True, verbose_name='Date de fin'),
        ),
    ]
